name: 02 - Workflow Events

on:
  push:
  pull_request:
  schedule:
    - cron: "5 5 6 7 8"
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "event type is:" ${{ github.event_name }}